function criarCaixaInserir() {
    const caixa = document.createElement('div')
    const p = document.createElement('p')
    const label1 = document.createElement('label')
    const label2 = document.createElement('label')
    const label3 = document.createElement('label')
    const label4 = document.createElement('label')
    const input1 = document.createElement('input')
    const input2 = document.createElement('input')
    const input3 = document.createElement('input')
    const input4 = document.createElement('input')
    const button1 = document.createElement('button')
    const button2 = document.createElement('button')
    const barraStatus = document.body.children[2]
    document.body.insertBefore(caixa, barraStatus)
    caixa.appendChild(label1)
    caixa.appendChild(input1)
    caixa.appendChild(p)
    caixa.appendChild(input2)
    caixa.appendChild(label2)
    caixa.appendChild(input3)
    caixa.appendChild(label3)
    caixa.appendChild(input4)
    caixa.appendChild(label4)
    caixa.appendChild(button1)
    caixa.appendChild(button2)
    caixa.setAttribute('id', 'caixa_inserir')
    input1.setAttribute('type', 'text')
    input1.setAttribute('placeholder', 'Inserir disciplina...')
    input1.setAttribute('id', 'input_disciplina')
    input2.setAttribute('type', 'checkbox')
    input2.setAttribute('checked', 'checked')
    input2.setAttribute('value', 'fta')
    input3.setAttribute('type', 'checkbox')
    input3.setAttribute('value', 'a1')
    input4.setAttribute('type', 'checkbox')
    input4.setAttribute('value', 'a2')
    button1.setAttribute('id', 'btn_inserir')
    button2.setAttribute('id', 'btn_fecharCaixa')
}